In [49]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import missingno as msno
import warnings
warnings.filterwarnings('ignore')

%matplotlib inline

In [50]:
cd Desktop/python/dacon/data

[WinError 3] 지정된 경로를 찾을 수 없습니다: 'Desktop/python/dacon/data'
C:\Users\us\Desktop\python\dacon\data

In [51]:
df_train = pd.read_csv('train.csv')
df_test = pd.read_csv('test.csv')

In [52]:
df_train

,ID,Age,Height,Weight,Position,PreferredFoot,AttackingWorkRate,DefensiveWorkRate,PaceTotal,ShootingTotal,...,CMRating,RMRating,LWBRating,CDMRating,RWBRating,LBRating,CBRating,RBRating,GKRating,Prospect
0,TRAIN_0000,21,182,82,CB,Right,Medium,Medium,4.6377,2.1053,...,4.9315,4.8649,6.1972,6.0000,6.1972,6.4286,6.5278,6.4286,0.875,0
1,TRAIN_0001,21,160,75,ST,Left,High,Medium,7.3913,7.3684,...,5.8904,6.4865,5.2113,4.4286,5.2113,5.0000,4.1667,5.0000,1.250,0
2,TRAIN_0002,18,165,60,RB,Right,Medium,Medium,6.2319,3.2895,...,4.9315,5.2703,5.7746,5.1429,5.7746,5.8571,5.0000,5.8571,0.750,0
3,TRAIN_0003,20,190,72,CB,Right,Medium,Medium,4.7826,1.0526,...,2.3288,2.2973,4.0845,3.7143,4.0845,4.5714,4.5833,4.5714,0.875,0
4,TRAIN_0004,21,181,77,ST,Right,High,Medium,8.2609,7.3684,...,6.3014,7.5676,5.2113,4.2857,5.2113,4.7143,3.3333,4.7143,1.125,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3014,TRAIN_3014,19,178,65,CAM,Right,Medium,Medium,5.9420,3.0263,...,5.0685,5.1351,5.0704,4.7143,5.0704,5.0000,4.3056,5.0000,0.500,1
3015,TRAIN_3015,19,172,60,CAM,Right,High,Low,7.1014,7.5000,...,7.8082,8.3784,6.4789,5.7143,6.4789,6.1429,4.0278,6.1429,0.875,0
3016,TRAIN_3016,21,173,70,CM,Right,Medium,High,4.7826,5.6579,...,7.1233,6.7568,7.3239,7.1429,7.3239,7.2857,6.5278,7.2857,1.000,0
3017,TRAIN_3017,21,182,77,CM,Right,High,High,6.3768,6.1842,...,8.3562,7.8378,8.4507,8.5714,8.4507,8.2857,7.7778,8.2857,1.125,0
3018,TRAIN_3018,20,170,62,RM,Right,High,Medium,7.8261,5.7895,...,5.0685,6.3514,4.7887,3.5714,4.7887,4.5714,2.7778,4.5714,0.875,0

In [53]:
df_train['Position'] = df_train['Position'].map({'CB' : 0, 'ST': 1, 'RB': 2, 'LB' : 3, 'GK': 4, 'CDM': 5, 'CAM': 6, 'CM' : 7, 'RM' : 8, 'LM' : 9,
       'RWB' : 10, 'LWB' : 11, 'RW' : 12, 'CF' : 13, 'LW' : 14})
df_test['Position'] = df_test['Position'].map({'CB' : 0, 'ST': 1, 'RB': 2, 'LB' : 3, 'GK': 4, 'CDM': 5, 'CAM': 6, 'CM' : 7, 'RM' : 8, 'LM' : 9,
       'RWB' : 10, 'LWB' : 11, 'RW' : 12, 'CF' : 13, 'LW' : 14})

In [54]:
df_train['PreferredFoot'] = df_train['PreferredFoot'].map({'Right' : 0, 'Left' : 1})
df_test['PreferredFoot'] = df_test['PreferredFoot'].map({'Right' : 0, 'Left' : 1})

df_train['AttackingWorkRate'] = df_train['AttackingWorkRate'].map({'Medium' : 0, 'High' : 1, 'Low' : 2})
df_test['AttackingWorkRate'] = df_test['AttackingWorkRate'].map({'Medium' : 0, 'High' : 1, 'Low' : 2})

df_train['DefensiveWorkRate'] = df_train['DefensiveWorkRate'].map({'Medium' : 0, 'High' : 1, 'Low' : 2})
df_test['DefensiveWorkRate'] = df_test['DefensiveWorkRate'].map({'Medium' : 0, 'High' : 1, 'Low' : 2})

In [55]:
df_train

,ID,Age,Height,Weight,Position,PreferredFoot,AttackingWorkRate,DefensiveWorkRate,PaceTotal,ShootingTotal,...,CMRating,RMRating,LWBRating,CDMRating,RWBRating,LBRating,CBRating,RBRating,GKRating,Prospect
0,TRAIN_0000,21,182,82,0,0,0,0,4.6377,2.1053,...,4.9315,4.8649,6.1972,6.0000,6.1972,6.4286,6.5278,6.4286,0.875,0
1,TRAIN_0001,21,160,75,1,1,1,0,7.3913,7.3684,...,5.8904,6.4865,5.2113,4.4286,5.2113,5.0000,4.1667,5.0000,1.250,0
2,TRAIN_0002,18,165,60,2,0,0,0,6.2319,3.2895,...,4.9315,5.2703,5.7746,5.1429,5.7746,5.8571,5.0000,5.8571,0.750,0
3,TRAIN_0003,20,190,72,0,0,0,0,4.7826,1.0526,...,2.3288,2.2973,4.0845,3.7143,4.0845,4.5714,4.5833,4.5714,0.875,0
4,TRAIN_0004,21,181,77,1,0,1,0,8.2609,7.3684,...,6.3014,7.5676,5.2113,4.2857,5.2113,4.7143,3.3333,4.7143,1.125,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3014,TRAIN_3014,19,178,65,6,0,0,0,5.9420,3.0263,...,5.0685,5.1351,5.0704,4.7143,5.0704,5.0000,4.3056,5.0000,0.500,1
3015,TRAIN_3015,19,172,60,6,0,1,2,7.1014,7.5000,...,7.8082,8.3784,6.4789,5.7143,6.4789,6.1429,4.0278,6.1429,0.875,0
3016,TRAIN_3016,21,173,70,7,0,0,1,4.7826,5.6579,...,7.1233,6.7568,7.3239,7.1429,7.3239,7.2857,6.5278,7.2857,1.000,0
3017,TRAIN_3017,21,182,77,7,0,1,1,6.3768,6.1842,...,8.3562,7.8378,8.4507,8.5714,8.4507,8.2857,7.7778,8.2857,1.125,0
3018,TRAIN_3018,20,170,62,8,0,1,0,7.8261,5.7895,...,5.0685,6.3514,4.7887,3.5714,4.7887,4.5714,2.7778,4.5714,0.875,0

In [56]:
df_test

,ID,Age,Height,Weight,Position,PreferredFoot,AttackingWorkRate,DefensiveWorkRate,PaceTotal,ShootingTotal,...,LMRating,CMRating,RMRating,LWBRating,CDMRating,RWBRating,LBRating,CBRating,RBRating,GKRating
0,TEST_0000,17,184,75,4,0,0,0,3.7681,5.3947,...,0.1351,0.5479,0.1351,0.2817,0.4286,0.2817,0.2857,0.2778,0.2857,5.500
1,TEST_0001,19,188,80,1,0,1,0,4.9275,4.8684,...,4.1892,3.4247,4.1892,3.0986,2.7143,3.0986,3.0000,3.0556,3.0000,0.750
2,TEST_0002,17,173,68,6,0,1,1,6.9565,6.3158,...,8.3784,8.6301,8.3784,8.3099,8.2857,8.3099,8.1429,7.0833,8.1429,1.125
3,TEST_0003,20,178,69,6,0,0,0,6.8116,6.4474,...,7.1622,6.7123,7.1622,5.6338,5.1429,5.6338,5.2857,4.1667,5.2857,1.375
4,TEST_0004,19,176,72,6,1,1,2,5.5072,4.7368,...,5.9459,5.4795,5.9459,5.0704,4.7143,5.0704,4.8571,4.0278,4.8571,0.750
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1621,TEST_1621,19,178,64,6,0,0,0,4.3478,4.6053,...,5.6757,5.3425,5.6757,4.7887,4.2857,4.7887,4.5714,3.6111,4.5714,0.750
1622,TEST_1622,20,179,73,5,0,0,0,5.3623,2.1053,...,4.4595,4.7945,4.4595,5.4930,5.4286,5.4930,5.7143,5.4167,5.7143,0.875
1623,TEST_1623,21,177,75,7,1,0,0,5.5072,4.8684,...,6.2162,6.3014,6.2162,6.1972,6.0000,6.1972,6.0000,5.2778,6.0000,0.750
1624,TEST_1624,18,176,66,6,1,0,0,5.0725,3.8158,...,5.1351,5.0685,5.1351,4.6479,4.4286,4.6479,4.7143,4.0278,4.7143,1.000
1625,TEST_1625,18,194,90,0,0,0,0,5.2174,1.4474,...,2.8378,2.3288,2.8378,4.6479,4.0000,4.6479,5.0000,5.5556,5.0000,0.625

In [57]:
df_train.drop(['ID'], axis=1, inplace=True)
df_test.drop(['ID'], axis=1, inplace=True)

In [58]:
df_test.head()

,Age,Height,Weight,Position,PreferredFoot,AttackingWorkRate,DefensiveWorkRate,PaceTotal,ShootingTotal,PassingTotal,...,LMRating,CMRating,RMRating,LWBRating,CDMRating,RWBRating,LBRating,CBRating,RBRating,GKRating
0,17,184,75,4,0,0,0,3.7681,5.3947,4.8529,...,0.1351,0.5479,0.1351,0.2817,0.4286,0.2817,0.2857,0.2778,0.2857,5.500
1,19,188,80,1,0,1,0,4.9275,4.8684,1.6176,...,4.1892,3.4247,4.1892,3.0986,2.7143,3.0986,3.0000,3.0556,3.0000,0.750
2,17,173,68,6,0,1,1,6.9565,6.3158,7.6471,...,8.3784,8.6301,8.3784,8.3099,8.2857,8.3099,8.1429,7.0833,8.1429,1.125
3,20,178,69,6,0,0,0,6.8116,6.4474,5.4412,...,7.1622,6.7123,7.1622,5.6338,5.1429,5.6338,5.2857,4.1667,5.2857,1.375
4,19,176,72,6,1,1,2,5.5072,4.7368,4.5588,...,5.9459,5.4795,5.9459,5.0704,4.7143,5.0704,4.8571,4.0278,4.8571,0.750

In [59]:
df_train = pd.get_dummies(df_train, columns = ['Position', 'PreferredFoot', 'AttackingWorkRate', 'DefensiveWorkRate'])

In [60]:
df_test = pd.get_dummies(df_test, columns = ['Position', 'PreferredFoot', 'AttackingWorkRate', 'DefensiveWorkRate'])

In [61]:
df_train.head()

,Age,Height,Weight,PaceTotal,ShootingTotal,PassingTotal,DribblingTotal,DefendingTotal,PhysicalityTotal,Crossing,...,Position_13,Position_14,PreferredFoot_0,PreferredFoot_1,AttackingWorkRate_0,AttackingWorkRate_1,AttackingWorkRate_2,DefensiveWorkRate_0,DefensiveWorkRate_1,DefensiveWorkRate_2
0,21,182,82,4.6377,2.1053,3.2353,3.9394,6.3158,6.2295,4.8864,...,0,0,1,0,1,0,0,1,0,0
1,21,160,75,7.3913,7.3684,4.2647,5.9091,2.6316,6.2295,4.5455,...,0,0,0,1,0,1,0,1,0,0
2,18,165,60,6.2319,3.2895,3.9706,3.9394,4.8684,4.4262,5.9091,...,0,0,1,0,1,0,0,1,0,0
3,20,190,72,4.7826,1.0526,0.4412,0.3030,4.6053,4.0984,1.9318,...,0,0,1,0,1,0,0,1,0,0
4,21,181,77,8.2609,7.3684,5.4412,6.9697,1.3158,5.9016,6.8182,...,0,0,1,0,0,1,0,1,0,0

In [62]:
# binary-classification
from sklearn.ensemble import RandomForestClassifier
from sklearn import metrics
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

X_train = df_train.drop('Prospect', axis = 1).values
target_label = df_train['Prospect'].values
X_test = df_test.values

In [63]:
X_train

array([[ 21., 182.,  82., ...,   1.,   0.,   0.],
       [ 21., 160.,  75., ...,   1.,   0.,   0.],
       [ 18., 165.,  60., ...,   1.,   0.,   0.],
       ...,
       [ 21., 173.,  70., ...,   0.,   1.,   0.],
       [ 21., 182.,  77., ...,   0.,   1.,   0.],
       [ 20., 170.,  62., ...,   1.,   0.,   0.]])

In [64]:
scaler = StandardScaler()

X_scaled = scaler.fit_transform(X_train)
X_scaled

array([[ 1.10703799,  0.16291243,  1.3640146 , ...,  0.44765792,
        -0.33339467, -0.26778254],
       [ 1.10703799, -3.07282846,  0.29346121, ...,  0.44765792,
        -0.33339467, -0.26778254],
       [-1.32126016, -2.3374328 , -2.00058177, ...,  0.44765792,
        -0.33339467, -0.26778254],
       ...,
       [ 1.10703799, -1.16079975, -0.47121978, ..., -2.23384855,
         2.99944807, -0.26778254],
       [ 1.10703799,  0.16291243,  0.59933361, ..., -2.23384855,
         2.99944807, -0.26778254],
       [ 0.29760527, -1.60203715, -1.69470937, ...,  0.44765792,
        -0.33339467, -0.26778254]])

In [65]:
X_tr, X_vid, y_tr, y_vid = train_test_split(X_scaled, target_label, test_size=0.2, random_state=2)
model = RandomForestClassifier()
model.fit(X_tr, y_tr)

prediction = model.predict(X_vid)
prediction

array([0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1,
       1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1,
       1, 0, 0, 0, 0, 1, 0, 1, 0, 0], dtype=int64)

In [66]:
print('총 {}명 중 {:.2f}% 정확도로 유망 맞춤'.format(y_vid.shape[0], 100 * metrics.accuracy_score(prediction, y_vid)))
'정확도 {:.2f}'.format((prediction == y_vid).sum() / prediction.shape[0])

총 604명 중 77.81% 정확도로 유망 맞춤

'정확도 0.78'

In [67]:
X_scaled_test = scaler.fit_transform(X_test)

In [68]:
X_scaled_test

array([[-2.12711603,  0.43129454,  0.24819094, ...,  0.47370623,
        -0.35611673, -0.27587776],
       [-0.50560142,  1.01074913,  0.99913711, ...,  0.47370623,
        -0.35611673, -0.27587776],
       [-2.12711603, -1.16220559, -0.80313369, ..., -2.11101299,
         2.808068  , -0.27587776],
       ...,
       [ 1.11591319, -0.582751  ,  0.24819094, ...,  0.47370623,
        -0.35611673, -0.27587776],
       [-1.31635872, -0.72761464, -1.10351216, ...,  0.47370623,
        -0.35611673, -0.27587776],
       [-1.31635872,  1.87993101,  2.50102943, ...,  0.47370623,
        -0.35611673, -0.27587776]])

In [69]:
prediction = model.predict(X_scaled_test)
prediction

array([1, 1, 0, ..., 0, 1, 0], dtype=int64)

In [70]:
submission = pd.read_csv('sample_submission.csv')
submission.head()

          ID  Prospect
0  TEST_0000         0
1  TEST_0001         0
2  TEST_0002         0
3  TEST_0003         0
4  TEST_0004         0

In [71]:
submission['Prospect'] = prediction
submission

             ID  Prospect
0     TEST_0000         1
1     TEST_0001         1
2     TEST_0002         0
3     TEST_0003         0
4     TEST_0004         1
...         ...       ...
1621  TEST_1621         1
1622  TEST_1622         0
1623  TEST_1623         0
1624  TEST_1624         1
1625  TEST_1625         0

[1626 rows x 2 columns]

In [72]:
submission.to_csv('submission.csv', index=False)